# PLUGIN MADE BY VictuallerDev/SyuVic

# Presets config

strength:
  custom-name: "&c&lStrength II"
  custom-lore: "&r\n&7Use this for &c&lStrength II&r&7.\n\n&eCooldown&7:&c {cooldown} seconds\n&eDuration&7:&c {cooldown} seconds"
  cooldown: 60
  amplifier: 1
  duration: 10

# GLOBAL

global:
  cooldown-global-ability: 16
  format-global-ability: "&r&l&5Partner Item's"