# PLUGIN MADE BY VictuallerDev/SyuVic

# Presets config

strength:
  custom-name: "&c&lStrength II"
  custom-lore: "&r\n&7Use this for &c&lStrength II&r&7.\n\n&eCooldown&7:&c {cooldown} seconds\n&eDuration&7:&c {cooldown} seconds"
  cooldown: 60
  amplifier: 1
  duration: 10

resistance:
  custom-name: "&7&lResistance III"
  custom-lore: "&r\n&7Use this for &7&lResistance III&r&7.\n\n&eCooldown&7:&c {cooldown} seconds\n&eDuration&7:&c {cooldown} seconds"
  cooldown: 60
  amplifier: 2
  duration: 10

potionrefill:
  custom-name: "&c&lPotion Refill"
  custom-lore: "&r\n&7Use this to fill your potion\n&7inventory where you have empty slots.\n\n&eCooldown&7:&c {cooldown} seconds"
  cooldown: 120
  amplifier: null
  duration: null

# GLOBAL

global:
  cooldown-global-ability: 16
  format-global-ability: "&r&l&5Partner Item's"